import {
  ArrowDownGray,
  ArrowDownPrimary,
  CheckGray,
  CheckPrimary,
  Close,
  BookmarkOutlined,
  Pen,
  FilterGray,
  FilterPrimary,
  Link,
  Pin,
  Globe,
  Home,
  Activity,
  Collection,
  Search,
  Like,
  Comment,
  View,
  CloseCircle,
  ArrowRightGray,
  GlobePrimary,
  Reply,
  Insta,
  DislikeGray,
  DislikePrimary,
  BadGray,
  BadPrimary,
  NeutralGray,
  NeutralPrimary,
  GoodGray,
  GoodPrimary,
  BestGray,
  BestPrimary,
  RadioGray,
  RadioPrimary,
  SwiperLeftButton,
  SwiperRightButton,
  BottmNavBarHome,
  BottmNavBarSearch,
  BottmNavBarWriting,
  BottmNavBarMypage,
} from "../../../public/icons";

export type TIcon = {
  src: string;
  alt: string;
};

const ICONS: { [key: string]: TIcon } = {
  ArrowDownGray: { src: ArrowDownGray, alt: "arrow" },
  ArrowDownPrimary: { src: ArrowDownPrimary, alt: "arrow" },
  ArrowRightGray: { src: ArrowRightGray, alt: "arrow" },
  CheckGray: { src: CheckGray, alt: "check" },
  CheckPrimary: { src: CheckPrimary, alt: "check" },
  Close: { src: Close, alt: "close" },
  BookmarkOutlined: { src: BookmarkOutlined, alt: "bookmark" },
  Pen: { src: Pen, alt: "write" },
  FilterGray: { src: FilterGray, alt: "filterGray" },
  FilterPrimary: { src: FilterPrimary, alt: "filterPrimary" },
  Link: { src: Link, alt: "link" },
  Pin: { src: Pin, alt: "pin" },
  Globe: { src: Globe, alt: "official site" },
  GlobePrimary: { src: GlobePrimary, alt: "official site" },
  Home: { src: Home, alt: "home" },
  Activity: { src: Activity, alt: "activity" },
  Collection: { src: Collection, alt: "collection" },
  Search: { src: Search, alt: "search" },
  Like: { src: Like, alt: "like" },
  Comment: { src: Comment, alt: "comment" },
  View: { src: View, alt: "view" },
  CloseCircle: { src: CloseCircle, alt: "close" },
  Reply: { src: Reply, alt: "reply" },
  Insta: { src: Insta, alt: "insta" },
  DislikeGray: { src: DislikeGray, alt: "dislike" },
  DislikePrimary: { src: DislikePrimary, alt: "dislike" },
  BadGray: { src: BadGray, alt: "bad" },
  BadPrimary: { src: BadPrimary, alt: "bad" },
  NeutralGray: { src: NeutralGray, alt: "neutral" },
  NeutralPrimary: { src: NeutralPrimary, alt: "neutral" },
  GoodGray: { src: GoodGray, alt: "good" },
  GoodPrimary: { src: GoodPrimary, alt: "good" },
  BestGray: { src: BestGray, alt: "best" },
  BestPrimary: { src: BestPrimary, alt: "best" },
  RadioGray: { src: RadioGray, alt: "radio" },
  RadioPrimary: { src: RadioPrimary, alt: "radio" },
  SwiperLeftButton: { src: SwiperLeftButton, alt: "swiper left" },
  SwiperRightButton: { src: SwiperRightButton, alt: "swiper right" },
  BottmNavBarHome: { src: BottmNavBarHome, alt: "home" },
  BottmNavBarSearch: { src: BottmNavBarSearch, alt: "search" },
  BottmNavBarWriting: { src: BottmNavBarWriting, alt: "writing" },
  BottmNavBarMypage: { src: BottmNavBarMypage, alt: "mypage" },
};

export default ICONS;
